#!/usr/bin/env bash
#
# Deploy the Google Ads MCP server to Google Cloud Run.
#
# Usage:
#   1. Copy deploy/config.env.example to deploy/config.env and fill in the values.
#   2. Run:  ./deploy/cloudrun.sh
#
# Safe to re-run: every step is idempotent, so if something fails partway
# through you can fix it and run the whole script again.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="${CONFIG_FILE:-$SCRIPT_DIR/config.env}"

if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "ERROR: $CONFIG_FILE not found."
  echo "Copy deploy/config.env.example to deploy/config.env and fill it in."
  exit 1
fi

# shellcheck disable=SC1090
source "$CONFIG_FILE"

: "${GOOGLE_PROJECT_ID:?Set GOOGLE_PROJECT_ID in $CONFIG_FILE}"
: "${GOOGLE_ADS_DEVELOPER_TOKEN:?Set GOOGLE_ADS_DEVELOPER_TOKEN in $CONFIG_FILE}"
: "${GOOGLE_ADS_MCP_OAUTH_CLIENT_ID:?Set GOOGLE_ADS_MCP_OAUTH_CLIENT_ID in $CONFIG_FILE}"
: "${GOOGLE_ADS_MCP_OAUTH_CLIENT_SECRET:?Set GOOGLE_ADS_MCP_OAUTH_CLIENT_SECRET in $CONFIG_FILE}"

REGION="${REGION:-us-central1}"
SERVICE="${SERVICE:-google-ads-mcp}"
AR_REPO="${AR_REPO:-mcp-servers}"
IMAGE="${REGION}-docker.pkg.dev/${GOOGLE_PROJECT_ID}/${AR_REPO}/${SERVICE}:latest"

# A stable JWT signing key keeps sign-ins valid across Cloud Run instances and
# redeploys. Generated once, then written back into the config file.
if [[ -z "${GOOGLE_ADS_MCP_JWT_SIGNING_KEY:-}" ]]; then
  GOOGLE_ADS_MCP_JWT_SIGNING_KEY="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
  {
    echo ""
    echo "# Generated by deploy/cloudrun.sh - keep this stable across deploys."
    echo "GOOGLE_ADS_MCP_JWT_SIGNING_KEY=${GOOGLE_ADS_MCP_JWT_SIGNING_KEY}"
  } >> "$CONFIG_FILE"
  echo "==> Generated a JWT signing key and saved it to $CONFIG_FILE"
fi

echo "==> Project: ${GOOGLE_PROJECT_ID}   Region: ${REGION}   Service: ${SERVICE}"
gcloud config set project "$GOOGLE_PROJECT_ID" --quiet

echo "==> [1/7] Enabling required APIs (can take a minute the first time)"
# A permissions failure here returns pages of base64 diagnostics that bury the
# one line that matters, so translate it into the actual ask instead.
API_ERR="$(mktemp)"
trap 'rm -f "$API_ERR"' EXIT
if ! gcloud services enable \
  googleads.googleapis.com \
  run.googleapis.com \
  cloudbuild.googleapis.com \
  artifactregistry.googleapis.com \
  firestore.googleapis.com \
  --quiet 2>"$API_ERR"; then

  if grep -qE 'PERMISSION_DENIED|does not have permission|Permission denied' "$API_ERR"; then
    ACTIVE_ACCOUNT="$(gcloud config get-value account 2>/dev/null || echo 'your account')"
    cat >&2 <<EOM

========================================================================
STOPPED: not enough permissions on this project.

  Account: ${ACTIVE_ACCOUNT}
  Project: ${GOOGLE_PROJECT_ID}

Nothing has been changed. This is a Google Cloud access problem, not a
problem with your settings or this script.

Ask whoever administers the project to grant that account the Owner role
(roles/owner) on ${GOOGLE_PROJECT_ID}. If Owner is too broad for your
organisation, these are the individual roles this deployment needs:

  roles/serviceusage.serviceUsageAdmin   enable the APIs
  roles/run.admin                        create the Cloud Run service
  roles/cloudbuild.builds.editor         build the container image
  roles/artifactregistry.admin           store the built image
  roles/datastore.owner                  create the Firestore database
  roles/iam.serviceAccountUser           run the service as its account
  roles/resourcemanager.projectIamAdmin  grant that account Firestore access

Alternatively, create a new Google Cloud project yourself — you become its
Owner automatically — then create a new OAuth client in it and set
GOOGLE_PROJECT_ID in deploy/config.env to the new project.

Re-run this script once access is sorted. It is safe to run again.
========================================================================
EOM
  else
    cat "$API_ERR" >&2
  fi
  exit 1
fi

echo "==> [2/7] Ensuring a Firestore database exists (stores sign-in tokens)"
# Firestore's valid locations are not the same list as Cloud Run's regions, so
# the deploy region is only a default here. If it is rejected, show the real
# list rather than failing with a bare error.
FIRESTORE_LOCATION="${FIRESTORE_LOCATION:-$REGION}"
if gcloud firestore databases describe --database='(default)' --quiet >/dev/null 2>&1; then
  echo "    Firestore database already exists, skipping."
elif ! gcloud firestore databases create --location="$FIRESTORE_LOCATION" --quiet; then
  echo ""
  echo "ERROR: Could not create a Firestore database in '${FIRESTORE_LOCATION}'."
  echo "Firestore supports its own set of locations. Valid values are:"
  gcloud firestore locations list --format='value(locationId)' 2>/dev/null || true
  echo ""
  echo "Pick one, then re-run with it set, for example:"
  echo "  FIRESTORE_LOCATION=nam5 ./deploy/cloudrun.sh"
  exit 1
fi

echo "==> [3/7] Ensuring the Artifact Registry repository exists"
if gcloud artifacts repositories describe "$AR_REPO" --location="$REGION" --quiet >/dev/null 2>&1; then
  echo "    Repository '${AR_REPO}' already exists, skipping."
else
  gcloud artifacts repositories create "$AR_REPO" \
    --repository-format=docker --location="$REGION" --quiet
fi

echo "==> [4/7] Granting the Cloud Run service account access to Firestore"
# Done before the deploy so the service can reach Firestore the moment it
# starts, rather than erroring on the first sign-in while IAM propagates.
PROJECT_NUMBER="$(gcloud projects describe "$GOOGLE_PROJECT_ID" --format='value(projectNumber)')"
RUNTIME_SA="${RUNTIME_SA:-${PROJECT_NUMBER}-compute@developer.gserviceaccount.com}"
gcloud projects add-iam-policy-binding "$GOOGLE_PROJECT_ID" \
  --member="serviceAccount:${RUNTIME_SA}" \
  --role="roles/datastore.user" \
  --condition=None --quiet >/dev/null
echo "    Granted roles/datastore.user to ${RUNTIME_SA}"

build_with_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "ERROR: docker is not available, so the local build cannot be used." >&2
    return 1
  fi
  echo "    Building locally with Docker and pushing to Artifact Registry."
  gcloud auth configure-docker "${REGION}-docker.pkg.dev" --quiet
  docker build -t "$IMAGE" "$REPO_DIR"
  docker push "$IMAGE"
}

# BUILD_METHOD: auto (default) tries Cloud Build and falls back to a local
# Docker build if Cloud Build is blocked from its staging bucket; 'docker' and
# 'cloudbuild' force one or the other.
BUILD_METHOD="${BUILD_METHOD:-auto}"

echo "==> [5/7] Building the container image (method: ${BUILD_METHOD})"
if [[ "$BUILD_METHOD" == "docker" ]]; then
  build_with_docker
else
  BUILD_ERR="$(mktemp)"
  trap 'rm -f "$API_ERR" "$BUILD_ERR"' EXIT
  if ! gcloud builds submit "$REPO_DIR" --tag "$IMAGE" --quiet 2>&1 | tee "$BUILD_ERR"; then :; fi
  if grep -qE 'forbidden from accessing the bucket|does not have storage\.|storage\.buckets\.(create|get)|PERMISSION_DENIED.*bucket' "$BUILD_ERR"; then
    if [[ "$BUILD_METHOD" == "cloudbuild" ]]; then
      cat >&2 <<'EOM'

========================================================================
STOPPED: Cloud Build cannot reach its staging bucket.

`gcloud builds submit` uploads the source to gs://<project>_cloudbuild, and
your account is not allowed to use that bucket. roles/cloudbuild.builds.editor
does not cover it.

Two ways forward:
  1. Ask your administrator for roles/storage.admin on the project, then
     re-run this script.
  2. Skip Cloud Build entirely and build locally instead:
       BUILD_METHOD=docker ./deploy/cloudrun.sh
     This needs no extra permissions - it builds the image on this machine and
     pushes it straight to Artifact Registry, which you can already write to.
========================================================================
EOM
      exit 1
    fi
    echo ""
    echo "    Cloud Build is blocked from its staging bucket; building locally instead."
    echo "    (No extra permissions needed - pushing straight to Artifact Registry.)"
    build_with_docker
  elif ! gcloud artifacts docker images describe "$IMAGE" --quiet >/dev/null 2>&1; then
    echo "ERROR: the image was not produced. See the build output above." >&2
    exit 1
  fi
fi

echo "==> [6/7] Deploying to Cloud Run"
# Note: --allow-unauthenticated is required. Claude's servers must be able to
# reach the endpoint; access is then controlled by the server's own Google
# OAuth sign-in, which only admits users who already have Google Ads access.
ENV_VARS="GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}"
ENV_VARS+=",GOOGLE_ADS_DEVELOPER_TOKEN=${GOOGLE_ADS_DEVELOPER_TOKEN}"
ENV_VARS+=",GOOGLE_ADS_MCP_OAUTH_CLIENT_ID=${GOOGLE_ADS_MCP_OAUTH_CLIENT_ID}"
ENV_VARS+=",GOOGLE_ADS_MCP_OAUTH_CLIENT_SECRET=${GOOGLE_ADS_MCP_OAUTH_CLIENT_SECRET}"
ENV_VARS+=",GOOGLE_ADS_MCP_JWT_SIGNING_KEY=${GOOGLE_ADS_MCP_JWT_SIGNING_KEY}"
ENV_VARS+=",GOOGLE_ADS_MCP_STORAGE_TYPE=firestore"
ENV_VARS+=",FASTMCP_HOST=0.0.0.0"
if [[ -n "${GOOGLE_ADS_LOGIN_CUSTOMER_ID:-}" ]]; then
  ENV_VARS+=",GOOGLE_ADS_LOGIN_CUSTOMER_ID=${GOOGLE_ADS_LOGIN_CUSTOMER_ID}"
fi

gcloud run deploy "$SERVICE" \
  --image "$IMAGE" \
  --platform managed \
  --region "$REGION" \
  --allow-unauthenticated \
  --set-env-vars="$ENV_VARS" \
  --quiet

SERVICE_URL="$(gcloud run services describe "$SERVICE" \
  --region "$REGION" --format='value(status.url)')"

echo "==> [7/7] Setting the service's own base URL"
# The server needs to know its own public address to build the OAuth redirect,
# and that address only exists once Cloud Run has created the service.
gcloud run services update "$SERVICE" \
  --region "$REGION" \
  --update-env-vars="GOOGLE_ADS_MCP_BASE_URL=${SERVICE_URL}" \
  --quiet

cat <<EOF

========================================================================
Deployed.

  MCP endpoint:  ${SERVICE_URL}/mcp

ONE MANUAL STEP IS LEFT. Add this exact redirect URI to your OAuth client
(Cloud Console -> APIs & Services -> Credentials -> your Web application
client -> Authorised redirect URIs -> Add URI -> Save):

  ${SERVICE_URL}/auth/callback

Then add this as a custom connector in Claude and sign in:

  ${SERVICE_URL}/mcp
========================================================================
EOF
