#!/usr/bin/env bash
#
# Deploy the Google Ads MCP server to Google Cloud Run.
#
# Usage:
#   1. Copy deploy/config.env.example to deploy/config.env and fill in the values.
#   2. Run:  ./deploy/cloudrun.sh
#
# Safe to re-run: every step is idempotent, so if something fails partway
# through you can fix it and run the whole script again.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="${CONFIG_FILE:-$SCRIPT_DIR/config.env}"

if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "ERROR: $CONFIG_FILE not found."
  echo "Copy deploy/config.env.example to deploy/config.env and fill it in."
  exit 1
fi

# shellcheck disable=SC1090
source "$CONFIG_FILE"

: "${GOOGLE_PROJECT_ID:?Set GOOGLE_PROJECT_ID in $CONFIG_FILE}"
: "${GOOGLE_ADS_DEVELOPER_TOKEN:?Set GOOGLE_ADS_DEVELOPER_TOKEN in $CONFIG_FILE}"
: "${GOOGLE_ADS_MCP_OAUTH_CLIENT_ID:?Set GOOGLE_ADS_MCP_OAUTH_CLIENT_ID in $CONFIG_FILE}"
: "${GOOGLE_ADS_MCP_OAUTH_CLIENT_SECRET:?Set GOOGLE_ADS_MCP_OAUTH_CLIENT_SECRET in $CONFIG_FILE}"

REGION="${REGION:-us-central1}"
SERVICE="${SERVICE:-google-ads-mcp}"
AR_REPO="${AR_REPO:-mcp-servers}"
IMAGE="${REGION}-docker.pkg.dev/${GOOGLE_PROJECT_ID}/${AR_REPO}/${SERVICE}:latest"

# A stable JWT signing key keeps sign-ins valid across Cloud Run instances and
# redeploys. Generated once, then written back into the config file.
if [[ -z "${GOOGLE_ADS_MCP_JWT_SIGNING_KEY:-}" ]]; then
  GOOGLE_ADS_MCP_JWT_SIGNING_KEY="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
  {
    echo ""
    echo "# Generated by deploy/cloudrun.sh - keep this stable across deploys."
    echo "GOOGLE_ADS_MCP_JWT_SIGNING_KEY=${GOOGLE_ADS_MCP_JWT_SIGNING_KEY}"
  } >> "$CONFIG_FILE"
  echo "==> Generated a JWT signing key and saved it to $CONFIG_FILE"
fi

echo "==> Project: ${GOOGLE_PROJECT_ID}   Region: ${REGION}   Service: ${SERVICE}"
gcloud config set project "$GOOGLE_PROJECT_ID" --quiet

echo "==> [1/6] Enabling required APIs (can take a minute the first time)"
gcloud services enable \
  googleads.googleapis.com \
  run.googleapis.com \
  cloudbuild.googleapis.com \
  artifactregistry.googleapis.com \
  firestore.googleapis.com \
  --quiet

echo "==> [2/6] Ensuring a Firestore database exists (stores sign-in tokens)"
if gcloud firestore databases describe --database='(default)' --quiet >/dev/null 2>&1; then
  echo "    Firestore database already exists, skipping."
else
  gcloud firestore databases create --location="$REGION" --quiet
fi

echo "==> [3/6] Ensuring the Artifact Registry repository exists"
if gcloud artifacts repositories describe "$AR_REPO" --location="$REGION" --quiet >/dev/null 2>&1; then
  echo "    Repository '${AR_REPO}' already exists, skipping."
else
  gcloud artifacts repositories create "$AR_REPO" \
    --repository-format=docker --location="$REGION" --quiet
fi

echo "==> [4/6] Building the container image with Cloud Build"
gcloud builds submit "$REPO_DIR" --tag "$IMAGE" --quiet

echo "==> [5/6] Deploying to Cloud Run"
# Note: --allow-unauthenticated is required. Claude's servers must be able to
# reach the endpoint; access is then controlled by the server's own Google
# OAuth sign-in, which only admits users who already have Google Ads access.
ENV_VARS="GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}"
ENV_VARS+=",GOOGLE_ADS_DEVELOPER_TOKEN=${GOOGLE_ADS_DEVELOPER_TOKEN}"
ENV_VARS+=",GOOGLE_ADS_MCP_OAUTH_CLIENT_ID=${GOOGLE_ADS_MCP_OAUTH_CLIENT_ID}"
ENV_VARS+=",GOOGLE_ADS_MCP_OAUTH_CLIENT_SECRET=${GOOGLE_ADS_MCP_OAUTH_CLIENT_SECRET}"
ENV_VARS+=",GOOGLE_ADS_MCP_JWT_SIGNING_KEY=${GOOGLE_ADS_MCP_JWT_SIGNING_KEY}"
ENV_VARS+=",GOOGLE_ADS_MCP_STORAGE_TYPE=firestore"
ENV_VARS+=",FASTMCP_HOST=0.0.0.0"
if [[ -n "${GOOGLE_ADS_LOGIN_CUSTOMER_ID:-}" ]]; then
  ENV_VARS+=",GOOGLE_ADS_LOGIN_CUSTOMER_ID=${GOOGLE_ADS_LOGIN_CUSTOMER_ID}"
fi

gcloud run deploy "$SERVICE" \
  --image "$IMAGE" \
  --platform managed \
  --region "$REGION" \
  --allow-unauthenticated \
  --set-env-vars="$ENV_VARS" \
  --quiet

SERVICE_URL="$(gcloud run services describe "$SERVICE" \
  --region "$REGION" --format='value(status.url)')"

echo "==> [6/6] Setting the service's own base URL and granting Firestore access"
gcloud run services update "$SERVICE" \
  --region "$REGION" \
  --update-env-vars="GOOGLE_ADS_MCP_BASE_URL=${SERVICE_URL}" \
  --quiet

PROJECT_NUMBER="$(gcloud projects describe "$GOOGLE_PROJECT_ID" --format='value(projectNumber)')"
RUNTIME_SA="${PROJECT_NUMBER}-compute@developer.gserviceaccount.com"
gcloud projects add-iam-policy-binding "$GOOGLE_PROJECT_ID" \
  --member="serviceAccount:${RUNTIME_SA}" \
  --role="roles/datastore.user" \
  --condition=None --quiet >/dev/null

cat <<EOF

========================================================================
Deployed.

  MCP endpoint:  ${SERVICE_URL}/mcp

ONE MANUAL STEP IS LEFT. Add this exact redirect URI to your OAuth client
(Cloud Console -> APIs & Services -> Credentials -> your Web application
client -> Authorised redirect URIs -> Add URI -> Save):

  ${SERVICE_URL}/auth/callback

Then add this as a custom connector in Claude and sign in:

  ${SERVICE_URL}/mcp
========================================================================
EOF
